language: c
env:
  - CABALVER=1.22 GHCVER=7.6.3
  - CABALVER=1.22 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.1
  - CABALVER=1.22 GHCVER=head

matrix:
  allow_failures:
    - env: CABALVER=1.22 GHCVER=head

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry cabal update

  # Installing cabal and ghc
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal install --only-dependencies --enable-tests
  
script:
  - cabal configure --enable-tests && cabal build && cabal test

notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#haskell-math"
